name: Dynamic Secret Export
on:
  workflow_dispatch:

jobs:
  export-secrets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['prod', 'test']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate secrets file
        env:
          # Single source of truth: Define secret names ONCE
          SECRET_NAMES: 'AZURE_CLIENT_ID DATABASE_URL API_KEY'  # Space-separated
          
          # GitHub Secrets must be manually mapped (limitation)
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          # Secure setup
          mkdir -p secrets/${{ matrix.environment }}
          chmod 700 secrets/${{ matrix.environment }}
          set +x

          # Generate the file dynamically
          SECRETS_FILE="secrets/${{ matrix.environment }}/secrets.env"
          for secret_name in $SECRET_NAMES; do
            # Indirect variable reference (bash feature)
            secret_value="${!secret_name}"
            echo "${secret_name}=${secret_value}" >> "$SECRETS_FILE"
          done

          echo "ENVIRONMENT=${{ matrix.environment }}" >> "$SECRETS_FILE"
          set -x
          chmod 600 "$SECRETS_FILE"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.environment }}-secrets
          path: secrets/${{ matrix.environment }}/secrets.env
          retention-days: 1
