name: Dynamic Secret Export

on:
  workflow_dispatch:

jobs:
  export-secrets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['prod', 'test']
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate secrets file
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          mkdir -p "secrets"
          chmod 700 "secrets"
          
          SECRETS_FILE="secrets/${{ matrix.environment }}.env"
          
          cat > "$SECRETS_FILE" <<EOL
          # Environment-specific secrets
          AZURE_CLIENT_ID='${AZURE_CLIENT_ID}'
          DATABASE_URL='${DATABASE_URL}'
          API_KEY='${API_KEY}'
          ENVIRONMENT='${{ matrix.environment }}'
          EOL
          
          chmod 600 "$SECRETS_FILE"

      - name: Upload secrets artifact
        uses: actions/upload-artifact@v4
        with:
          name: secrets-${{ matrix.environment }}
          path: secrets/${{ matrix.environment }}.env
          retention-days: 1

      - name: Cleanup secrets
        if: always()
        run: |
          rm -rf secrets/
