name: Secure Dynamic Secret Export

on:
  workflow_dispatch:

jobs:
  export-encrypted-secrets:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ['prod', 'test']
    environment: ${{ matrix.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate and encrypt secrets file
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          API_KEY: ${{ secrets.API_KEY }}
          ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
        run: |
          # Create directory with restricted permissions
          mkdir -p "secrets"
          chmod 700 "secrets"
          
          # Turn off command logging to prevent secrets from appearing in logs
          set +x
          
          SECRETS_FILE="secrets/${{ matrix.environment }}.env"
          ENCRYPTED_FILE="secrets/${{ matrix.environment }}.env.enc"
          
          # Create environment-specific secrets file
          cat > "$SECRETS_FILE" <<EOL
          # Environment-specific secrets
          AZURE_CLIENT_ID='${AZURE_CLIENT_ID}'
          DATABASE_URL='${DATABASE_URL}'
          API_KEY='${API_KEY}'
          ENVIRONMENT='${{ matrix.environment }}'
          EOL
          
          # Set strict file permissions
          chmod 600 "$SECRETS_FILE"
          
          # Encrypt the file
          openssl enc -aes-256-cbc -pbkdf2 -salt -in "$SECRETS_FILE" -out "$ENCRYPTED_FILE" -pass pass:"$ENCRYPTION_PASSWORD"
          
          # Remove the unencrypted file
          rm -f "$SECRETS_FILE"
          
          # Turn logging back on
          set -x

      - name: Upload encrypted secrets artifact
        uses: actions/upload-artifact@v4
        with:
          name: encrypted-secrets-${{ matrix.environment }}
          path: secrets/${{ matrix.environment }}.env.enc
          retention-days: 1

      - name: Cleanup
        if: always()
        run: |
          rm -rf secrets/
