name: Install Powershell module
on: workflow_dispatch

permissions:
  id-token: write
  contents: read
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: 'Az CLI login'
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: 'Install the powershell dependency'
        shell: pwsh
        run: |
          Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force -AllowClobber
          Import-Module -Name Az
