name: Build Linux Container Image and Push to ACR

on:
  [push]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: DockerTest
    steps:
   
    - uses: azure/docker-login@v1
      with:
        login-server: craazure.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    - run: |
        docker build . -t craazure.azurecr.io/dockertestapp:${{ github.sha }}
        docker push craazure.azurecr.io/dockertestapp:${{ github.sha }}
    
    - name: Log in with Azure
      uses: azure/login@v1
      with:
         creds: '${{ secrets.AZURE_CREDENTIALS }}'
         enable-AzPSSession: true

    - uses: azure/container-apps-deploy-action@v1
      with:
        acrName: craazure
        containerAppName: dockertest-app-20240126191323
        imageToDeploy: craazure.azurecr.io/dockertestapp:${{ github.sha }}
        resourceGroup: Robin-ResourceGroup