name: Secret Multiple WITHOUT ENC
on:
  workflow_dispatch:
jobs:
  create-and-delete:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create and secrets file
      env:
        ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
      run: |
        # Create directory with restricted permissions
        mkdir -p config
        chmod 700 config
        
        # Turn off command logging to prevent secrets from appearing in logs
        set +x
        
        # Create simple key-value pairs file
        cat > config/secrets.txt << EOF
        AZURE_CLIENT_ID=${{ secrets.AZURE_CLIENT_ID }}
        ENVIRONMENT=production
        EOF
        
        # Turn logging back on
        set -x
        
        # Set strict file permissions
        chmod 600 config/secrets.txt
        
        # Encrypt the file
        #openssl enc -aes-256-cbc -pbkdf2 -salt -in config/secrets.txt -out config/secrets.txt.enc -pass pass:"$ENCRYPTION_PASSWORD"
        
        # Remove the unencrypted file
        #rm -f config/secrets.txt
        
    - name: Upload as artifact
      uses: actions/upload-artifact@v4
      with:
        name: encrypted-secrets
        path: config/secrets.txt
        retention-days: 1
