name: SecretV2WithAutoDelete

on:
  workflow_dispatch:

jobs:
  create-and-delete:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create secret file
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
      run: |
        mkdir -p config
        echo "$MY_SECRET" > config/secret.txt
        chmod 600 config/secret.txt
        
    - name: Upload as artifact
      uses: actions/upload-artifact@v4
      with:
        name: secret-file
        path: config/secret.txt
        retention-days: 1
        
    - name: Get artifact ID
      id: get-artifact
      run: |
        # First wait briefly for artifact to be available
        sleep 15
        
        # Get artifact ID and set output
        ARTIFACT_ID=$(gh api repos/$GITHUB_REPOSITORY/actions/artifacts \
          --jq '.artifacts[] | select(.name == "secret-file") | .id')
        
        # Properly escape and set output
        echo "artifact_id=${ARTIFACT_ID}" >> $GITHUB_OUTPUT
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Delete after 5 minutes
      run: |
        echo "Artifact ID to delete: ${{ steps.get-artifact.outputs.artifact_id }}"
        sleep 300  # Wait 5 minutes
        
        # Delete the artifact
        gh api -X DELETE \
          repos/$GITHUB_REPOSITORY/actions/artifacts/${{ steps.get-artifact.outputs.artifact_id }} || \
          echo "Artifact already deleted or not found"
      env:
        GITHUB_TOKEN: ${{ github.token }}
