name: Save Secret to File

on:
  workflow_dispatch:

jobs:
  save-secret:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Save secret to file
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}  # Your GitHub secret
      run: |
        # Create a directory if needed
        mkdir -p config
        
        # Save secret to file (properly escaped)
        echo "$MY_SECRET" > config/secret.txt
        
        # Optional: Set restrictive permissions
        chmod 600 config/secret.txt
        
        # Verify the file was created (secret will be masked in logs)
        echo "File created at:"
        ls -la config/
