name: SecretV2Encryption
on:
  workflow_dispatch:
jobs:
  create-and-delete:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Create and encrypt secret file
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
        ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}
      run: |
        mkdir -p config
        echo "$MY_SECRET" > config/secret.txt
        chmod 600 config/secret.txt
        
        # Encrypt with OpenSSL
        openssl enc -aes-256-cbc -salt -in config/secret.txt -out config/secret.txt.enc -pass pass:"$ENCRYPTION_PASSWORD"
        
        # Remove the unencrypted file
        rm config/secret.txt
        
    - name: Upload as artifact
      uses: actions/upload-artifact@v4
      with:
        name: encrypted-secret-file
        path: config/secret.txt.enc
        retention-days: 1
